# Site settings
name: SPTO Qiang
title: SPTO Qiang
description: "Hello！我是郭志强，一名iOS开发者，现在在北京工作，有很强的求知欲，正在学习前端和小程序"
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Delete the lines you don't need
# about 5 elements are recomended
github_username: SPTOGUO
facebook_username: your_facebook_username_goes_here
twitter_username: SuperTOQ
weibo_username: 1854747423
blog_url: "/blogs"
email: guozhiqiang@loopeer.com
#public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"

# Author Settings
author-img: avator.jpg # add your photo


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "assets/img/avator.jpg"


front_img: yes
front_img_path: "assets/img/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "assets/img/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty





#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#permalink: ':title/'

site-twitter: #if your site has a twitter account, enter it here

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "blogs/page:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]